# Site
name: "The Nakamoto"
title: "The Nakamoto"
description: "An educational portal for sound money and technology."
tagline: "An educational portal for sound money and technology."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: 'thenakamoto.com'
baseurl: ''
google_analytics: 'UA-178101418-1'
disqus: 'thenakamoto-com'
mailchimp-list: 'https://thenakamoto.us20.list-manage.com/subscribe/post?u=a62d8de4abe2b1bdef7e13c98&amp;id=af36692f4c'
include: ["_pages"]
permalink: /:title/
twitter:
  username: TheNakamotoCom
  card: summary
  

# Authors
authors:
  tiaan:
    name: tiaan
    display_name: Tiaan Wolmarans
    gravatar: 1d4073f730790f1b0da3577939c2e02f
    email: tiaan@xxi.finance
    web: https://www.imtiaan.com
    twitter: https://twitter.com/ImTiaan
    description: "Founder of The Nakamoto, an educational portal for sound money and technology."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

